### ISSUE TITLE
Unable to retrieve password for i6

### ISSUE THREAD

**Issue by hardweb-it** [NickWaterton/Roomba980-Python#115]
Hello, 
I'm trying to retrieve password of my Roomba i6 (sku:i615840, and sw:lewis+22.52.5+2023-02-16-7e788e611c3+Firmware-Build+2880) but with no luck.

I tried in more ways with Ubuntu 20 and Python 3.8, and with Win 10 Powershell python 3.9. No one works and get always the same error

Trying with "local mode" using: ./password.py -R ROOMBA_IP_ADDRESS
I always get this:

```
2023-04-06 12:53:12 INFO [Roomba.Password] Roomba (Roomba) IP address is: 192.168.1.152
2023-04-06 12:53:15 ERROR [Roomba.Password] Unable to Connect to roomba at ip 192.168.1.152, make sure nothing else is connected (app?), as only one connection at a time is allowed
2023-04-06 12:53:15 ERROR [Roomba.Password] Unable to get password from roomba
2023-04-06 12:53:15 ERROR [Roomba.Password] Error getting password for robot Roomba at ip192.168.1.152, received 0 bytes. Follow the instructions and try again.

```

And also tried with Cloud mode with: ./password.py "username" "password"
```
2023-04-06 12:48:03 INFO [Roomba.Password] Getting Roomba information from iRobot aws cloud...
2023-04-06 12:48:04 DEBUG [urllib3.connectionpool] Starting new HTTPS connection (1): disc-prod.iot.irobotapi.com:443
2023-04-06 12:48:04 DEBUG [urllib3.connectionpool] https://disc-prod.iot.irobotapi.com:443 "GET /v1/discover/endpoints?country_code=US HTTP/1.1" 200 1789
2023-04-06 12:48:04 DEBUG [urllib3.connectionpool] Starting new HTTPS connection (1): accounts.us1.gigya.com:443
2023-04-06 12:48:05 DEBUG [urllib3.connectionpool] https://accounts.us1.gigya.com:443 "POST /accounts.login HTTP/1.1" 200 217
Traceback (most recent call last):
  File "./password.py", line 294, in <module>
    main()
  File "./password.py", line 291, in main
    get_passwd.get_password()
  File "./password.py", line 119, in get_password
    iRobot.login()
  File "/root/Roomba980-Python/roomba/getcloudpassword.py", line 107, in login
    uid = response['UID']
KeyError: 'UID'
```

Any suggestion?
Thank you in advance

**Comment by NickWaterton** [comment]
There is generally two reasons why you can't connect:

1) Unable to Connect to roomba Roomba, make sure nothing else is connected (app?), as only one connection at a time is allowed
2) Encryption has changed

If it's 1), you have to force close the app on your phone. One HA has connected, you can open the app again, and it will use the cloud connection, instead of the local connection.

If it's 2), it's more of a problem, because the program has to be adapted to the new encryption, and that's hard to do as I don't have an i6 to test it on.

**Comment by hardweb-it** [comment]
Finally I was able to manage the issue.

That's how (in this exact order):

1. Open the official "iRobot APP" and reset the device
2. Reset iRobot account's password (by removing "$" char or any other chars which do the issue, and substitute them with any other symbol...for example using "!" << tested and working)
3. Reconnect Roomba device after reset, to the WiFi Network, such as the first installation.
4. Run the ./password.py "username" "password" command
5. Now the script is able to retrieve the new decoded password from cloud.
6. Open iRobot APP, tap on MENU, go to "Account" and then tap on "Close session" button at the bottom.
7. Repeat the step n.6 for all other local devices which have iRobot app connected to the cloud.
8. Now open HA -> Settings -> Device -> Roomba and click on the "configure" button.
9. Type (or copy & paste) the password grabbed at the fifth step.
10. Now the HA Roomba configuration should work fine!
11. Open iRobot APP on your devices and then login again.

Before doing all that things, I tried to only change my account password, logout from APP, and get the new one decoded, but anyway the HA connection doesn't work as excpected.

After perform the full process, it goes fine!
Hope this can help other people!

Thanks for your time.

**Comment by NickWaterton** [comment]
Glad you figured it out. The whole "only one thing can be connected at a time" thing is a PITA.

Persistence pays off!

**Comment by GottiL** [comment]
@hardweb-it Thank you! for over a year I have been trying to setup. After  password update, & restore, everything was auto detected via HA.
