### ISSUE TITLE
Can't get username/blid and password from iRobot cloud - urllib3.packages.six.moves error

### ISSUE THREAD

**Issue by detail9** [NickWaterton/Roomba980-Python#121]
Hi,

I'm attempting to run password.py to get the username/blid and password from iRobot cloud.  I'm using Python 3.12.0 on Windows 11 with _requests_ module version 2.31.0. I also installed all other modules using `pip3 install -r requirements.txt` as described [here](https://github.com/NickWaterton/Roomba980-Python#install).

Below is the Traceback error I get. It seems to have something to do with a module named _urllib3.packages.six.moves_ but after Googling that I have no idea what that actually is. I have _urllib3_ version 1.25.11 installed, if that matters.

```
2023-11-19 20:18:29 INFO [Roomba.Password] Getting Roomba information from iRobot aws cloud...
Traceback (most recent call last):
  File "C:\Users\username\Documents\Github\Roomba980-Python\roomba\password.py", line 294, in <module>
    main()
  File "C:\Users\username\Documents\Github\Roomba980-Python\roomba\password.py", line 291, in main
    get_passwd.get_password()
  File "C:\Users\username\Documents\Github\Roomba980-Python\roomba\password.py", line 117, in get_password
    from getcloudpassword import irobotAuth
  File "C:\Users\username\Documents\Github\Roomba980-Python\roomba\getcloudpassword.py", line 20, in <module>
    import requests
  File "C:\Users\username\AppData\Roaming\Python\Python312\site-packages\requests\__init__.py", line 43, in <module>
    import urllib3
  File "C:\Users\username\AppData\Roaming\Python\Python312\site-packages\urllib3\__init__.py", line 7, in <module>
    from .connectionpool import HTTPConnectionPool, HTTPSConnectionPool, connection_from_url
  File "C:\Users\username\AppData\Roaming\Python\Python312\site-packages\urllib3\connectionpool.py", line 11, in <module>
    from .exceptions import (
  File "C:\Users\username\AppData\Roaming\Python\Python312\site-packages\urllib3\exceptions.py", line 2, in <module>
    from .packages.six.moves.http_client import IncompleteRead as httplib_IncompleteRead
ModuleNotFoundError: No module named 'urllib3.packages.six.moves'
```

I am new to Python (this is actually my first "project" working in it) so hopefully I just overlooked something simple.

**Comment by detail9** [comment]
Additional info about my setup. Below are all packages I have installed.

- aiohttp==3.9.0
- aiosignal==1.3.1
- attrs==23.1.0
- certifi==2023.11.17
- charset-normalizer==3.3.2
- frozenlist==1.4.0
- idna==3.4
- multidict==6.0.4
- numpy==1.26.2
- opencv-python==4.8.1.78
- paho-mqtt==1.6.1
- Pillow==10.1.0
- requests==2.31.0
- urllib3==1.25.11
- yarl==1.9.2

**Comment by NickWaterton** [comment]
Python 3.12 is not supported. 3.10 is the latest version supported.
