### ISSUE TITLE
NO module named password

### ISSUE THREAD

**Issue by Darbos** [NickWaterton/Roomba980-Python#19]
Hi Nick,

Thanks for the great work here.  You have an idea on why I might be getting the below error?  Im trying to just get the bld and pw for the roomba.  I cloned the repo and when i run python roomba.py I get the below..

Traceback (most recent call last):
  File "roomba.py", line 25, in <module>
    from roomba.password import Password
  File "/home/pi/roomba_pw/Roomba980-Python/roomba/roomba.py", line 25, in <module>
    from roomba.password import Password
ImportError: No module named password

**Comment by Darbos** [comment]
I did the full install and when i run install i get 

CV or numpy module not found, falling back to PIL
PIL module not found, maps are disabled
CV or numpy module not found, falling back to PIL
PIL module not found, maps are disabled
[I 2017-09-15 13:32:49,664] *******************
[I 2017-09-15 13:32:49,665] * Program Started *
[I 2017-09-15 13:32:49,665] *******************
[I 2017-09-15 13:32:49,666] Roomba.py Version: 1.2.1
[I 2017-09-15 13:32:49,666] Python Version: 3.6.2 (default, Sep  7 2017, 11:20:01) [GCC 6.3.0 20170516]
[I 2017-09-15 13:32:49,667] Paho MQTT Version: 1.3.0
Traceback (most recent call last):
  File "/usr/local/bin/roomba", line 11, in <module>
    load_entry_point('roombapy==1.3.1.post1', 'console_scripts', 'roomba')()
  File "/usr/local/lib/python3.6/site-packages/roomba/__main__.py", line 455, in main
    if HAVE_CV2:
NameError: name 'HAVE_CV2' is not defined

**Comment by NickWaterton** [comment]
@Darbos ,

Thanks for the feedback, @pschmitt reworked the code a while back, and I think some errors have crept in. There seems to be some sort of circular import loop going on, and possibly to functionality if you don't have opencv has been compromised.

I'm looking into it.

**Comment by Darbos** [comment]
Thank you!!  I tried to install open cv like mentioned but it does not find the package.

**Comment by NickWaterton** [comment]
you may have an older version of pip, older versions do not install opencv.

To upgrade pip, try:running 
```pip install --upgrade pip```

then try installing opencv-python (worked for me after upgrading pip)

**Comment by Darbos** [comment]
Thanks I tried that a little earlier and it says its good.
pi@sql_server:~/roomba_pw/Roomba980-Python/roomba $ sudo pip install --upgrade pip
Requirement already up-to-date: pip in /usr/lib/python2.7/dist-packages
pi@sql_server:~/roomba_pw/Roomba980-Python/roomba $ pip list
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
cryptography (1.7.1)
enum34 (1.1.6)
idna (2.2)
ipaddress (1.0.17)
Jinja2 (2.8)
keyring (10.1)
keyrings.alt (1.3)
MarkupSafe (0.23)
mysqlclient (1.3.7)
olefile (0.44)
pip (9.0.1)
psutil (5.0.1)
pyasn1 (0.1.9)
pycrypto (2.6.1)
pygobject (3.22.0)
pyxdg (0.25)
RPi.GPIO (0.6.3)
SecretStorage (2.3.1)
setuptools (33.1.1)
six (1.10.0)
WebIOPi (0.7.1)
wheel (0.29.0)

**Comment by Darbos** [comment]
I was able to get this far...

pi@sql_server:~/roomba_pw/dorita980 $ sudo npm run getpassword 192.168.86.118

> dorita980@3.0.11 getpassword /home/pi/roomba_pw/dorita980
> node ./bin/getpassword.js "192.168.86.118"

Make sure your robot is on the Home Base and powered on (green lights on). Then press and hold the HOME button on your robot until it plays a series of tones (about 2 seconds). Release the button and your robot will flash WIFI light.
Then press any key here...
Robot Data:
{ ver: '3',
  hostname: 'Roomba-3143C91031944720',
  robotname: 'Roomba',
  ip: '192.168.86.118',
  mac: 'F0:03:8C:E0:EE:B4',
  sw: '3.2.7',
  sku: 'R690020',
  nc: 0,
  proto: 'mqtt',
  cap: { ota: 1, eco: 1, svcConf: 1 },
  blid: '3143C91031944720' }
Error getting password. Follow the instructions and try again.
pi@sql_server:~/roomba_pw/dorita980 $

**Comment by NickWaterton** [comment]
I got that far in the past with Dorita, I believe that it’s because your node.js is out of date.

I should have a fixed python version uploaded soon.

Nick Waterton P.Eng.
National Support Leader - Nuclear Medicine, PET and RP
GE Healthcare

GE imagination at work

**Comment by Darbos** [comment]
AHHHH, lol you were correct!!!  thank you for taking the time to assist me.  updated node and got it!!

**Comment by NickWaterton** [comment]
OK, just pushed a new commit, try pulling it, and see if everything works now...

once it's installed (with ```python ./setup.py install```) you just need to run ```roomba``` (with whatever options you like)

**Comment by Darbos** [comment]
Thank you! I was really looking for the un and pw so I can control it with my home assistant implementation. Working perfect!
