### ISSUE TITLE
Not able to connect Roomba 980

### ISSUE THREAD

**Issue by Mannshoch** [NickWaterton/Roomba980-Python#70]
Even I do a portscan on the IP of my roomba `nmap $IP -p1-65535` I do not get any open port

```
user:~/.local/bin$ ./roomba-getpassword -R $IP
waiting on port: 5678 for data
No Roombas found, try again...
```

**Comment by taugusti** [comment]
I have the same issue - started about a week ago - I do not know if it is related to new roomba firmware or something else. I have not actively changed anything, but the problems started when we had a power loss in the area.

I use home assistant if that means anything...
The iRobot app is able to communicate with the vacuum cleaner.

When I run getpassword.py I get:

```
Connection Error [WinError 10061] No connection could be made because the target machine actively refused it
Traceback (most recent call last):
  File "C:\Users\thoma\OneDrive\innoworks\Div\tvedvej50\HomeAssistant\roomba\Roomba980-Python-master\roomba\getpassword.py", line 39, in <module>
    main()
  File "C:\Users\thoma\OneDrive\innoworks\Div\tvedvej50\HomeAssistant\roomba\Roomba980-Python-master\roomba\getpassword.py", line 34, in main
    Password(file=arg.configfile)
  File "C:\Users\thoma\OneDrive\innoworks\Div\tvedvej50\HomeAssistant\roomba\Roomba980-Python-master\roomba\password.py", line 41, in __init__
    self.get_password()
  File "C:\Users\thoma\OneDrive\innoworks\Div\tvedvej50\HomeAssistant\roomba\Roomba980-Python-master\roomba\password.py", line 138, in get_password
    wrappedSocket.send(packet)
  File "C:\Users\thoma\AppData\Local\Programs\Python\Python37\lib\ssl.py", line 983, in send
    return super().send(data, flags)
socket.timeout: timed out
```

**Comment by Mannshoch** [comment]
Was able to get the passwort with: https://github.com/koalazak/dorita980#how-to-get-your-usernameblid-and-password
I learned that I had to press the Home button 2s to be able to connect.
