### ISSUE TITLE
Pyton 3.8 / Firmware 3.4 compatibility?

### ISSUE THREAD

**Issue by nightops** [NickWaterton/Roomba980-Python#76]
Running via a Windows 10 PC connected to same network as the Roomba 960.  Roomba has static IP.  Updated Python to 3.8 and executing roomba.py displays:
$ python roomba/roomba.py
roomba/roomba.py:30: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working
  from collections import OrderedDict, Mapping
Traceback (most recent call last):
  File "D:\Misc\Roomba\Roomba980-Python\roomba\roomba.py", line 32, in <module>
    from roomba.password import Password
ModuleNotFoundError: No module named 'roomba.password'; 'roomba' is not a package

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "roomba/roomba.py", line 32, in <module>
    from roomba.password import Password
  File "D:\Misc\Roomba\Roomba980-Python\roomba\roomba.py", line 34, in <module>
    from password import Password
  File "D:\Misc\Roomba\Roomba980-Python\roomba\password.py", line 6, in <module>
    import six
ModuleNotFoundError: No module named 'six'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "roomba/roomba.py", line 34, in <module>
    from password import Password
  File "D:\Misc\Roomba\Roomba980-Python\roomba\password.py", line 6, in <module>
    import six
ModuleNotFoundError: No module named 'six'

**Comment by coni77** [comment]
I had the same probem with Python 3.7.
The solution for me was to start cmd, go to the python folder and execute: pip install six
