### ISSUE TITLE
Cannot install script

### ISSUE THREAD

**Issue by Taurenlord** [NickWaterton/Roomba980-Python#83]
Hi Community, 

i have following error:

`
Collecting git+https://github.com/NickWaterton/Roomba980-Python.git
  Cloning https://github.com/NickWaterton/Roomba980-Python.git to /tmp/pip-CwsDqk-build
Requirement already satisfied: numpy in /usr/lib/python2.7/dist-packages (from Roomba980-Python==1.2.3)
Collecting opencv-python (from Roomba980-Python==1.2.3)
  Using cached https://files.pythonhosted.org/packages/a1/d6/8422797e35f8814b1d9842530566a949d9b5850a466321a6c1d5a99055ee/opencv-python-4.3.0.38.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-S370Ko/opencv-python/setup.py", line 448, in <module>
        main()
      File "/tmp/pip-build-S370Ko/opencv-python/setup.py", line 99, in main
        % {"ext": re.escape(sysconfig.get_config_var("EXT_SUFFIX"))}
      File "/usr/lib/python2.7/re.py", line 210, in escape
        s = list(pattern)
    TypeError: 'NoneType' object is not iterable

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-S370Ko/opencv-python/
root@APP02:~#
`

**Comment by NickWaterton** [comment]
You have some sort of problem installing opencv-python. you may need to install as su using sudo.

**Comment by tonlam** [comment]
Try `pip2 install opencv-python==4.2.0.32`

**Comment by NickWaterton** [comment]
You actually need opencv-contrib-python==3.2.0.7

Version 4 of opencv leaves out some important commands.
