### ISSUE TITLE
Got it working with Roomba i7 firmware 3.2.9 on WIN10 Python 3.7

### ISSUE THREAD

**Issue by emanuelgollob** [NickWaterton/Roomba980-Python#84]
**With paho-mqtt version 1.2.3  I got this error:**

[E 2020-09-10 10:56:46,243] Error setting TLS: Traceback (most recent call last):
  File "c:\users\emanu\anaconda3\envs\irobot\lib\site-packages\paho\mqtt\client.py", line 643, in tls_set
    f = open(ca_certs, "r")
FileNotFoundError: [Errno 2] No such file or directory: '/etc/ssl/certs/ca-certificates.crt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\emanu\anaconda3\envs\irobot\lib\site-packages\roomba\roomba.py", line 338, in setup_client
    tls_version=ssl.PROTOCOL_TLS, ciphers='DEFAULT@SECLEVEL=1')
  File "c:\users\emanu\anaconda3\envs\irobot\lib\site-packages\paho\mqtt\client.py", line 645, in tls_set
    raise IOError(ca_certs+": "+err.strerror)
OSError: /etc/ssl/certs/ca-certificates.crt: No such file or directory

**After replacing paho-mqtt version 1.2.3 with  paho-mqtt version 1.5.0 everything worked fine.
These package versions worked for me:**

appdirs==1.4.3
numpy==1.19.1
olefile==0.44
opencv-python==3.2.0.7
packaging==16.8
paho-mqtt==1.5.0
Pillow==6.2.0
pyparsing==2.2.0
six==1.10.0

**Comment by NickWaterton** [comment]
I will be posting a new Python 3.6 version in a few days. Supports 980, s9, Braava jet m6.

should fix most of these legacy issues.
